server:
  port: 8000
spring:
  application:
    name: EHR-SYSTEM
  datasource:
    url: jdbc:postgresql://localhost:5432/ehr_db
    username: postgres
    password: stan
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:  
      ddl-auto: update
    show-sql: true
  
jwt:
  secret: 0e7d5a5f9b1c7a8b3e2d6f0c4a9b8e1f5d7c3b9e8f1a0d2c6b4e8f9c1a0b3d5e
  expiration: 3600000